import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage();
page.on("console", m => console.log(`[${m.type()}] ${m.text()}`));
page.on("pageerror", e => console.log(`[PAGE ERROR] ${e.message}`));
page.on("requestfailed", r => console.log(`[FAILED] ${r.url()} - ${r.failure().errorText}`));
await page.goto("http://127.0.0.1:4173/search.html", { waitUntil: "domcontentloaded", timeout: 15000 });
await page.waitForTimeout(3000);
const html = await page.content();
console.log("Has results-grid:", html.includes("results-grid"));
console.log("Has result-card:", html.includes("result-card"));
console.log("Cat chips:", await page.evaluate(() => document.getElementById("cat-chips")?.innerHTML?.slice(0, 100) || "EMPTY"));
console.log("Results:", await page.evaluate(() => document.getElementById("results")?.innerHTML?.slice(0, 200) || "EMPTY"));
await browser.close();